class GameConfig:
    # 遊戲基本設定
    WORD_LENGTH = 5
    MAX_GUESSES = 6
    TIME_LIMIT_SECONDS = 180  # 多人模式的 3 分鐘限時
    
    # 系統提示訊息
    MSG_ALREADY_GUESSED = "已經猜過該單字囉"
    MSG_CORRECT = "完全正確！"
    MSG_WRONG = "繼續加油！"
    MSG_INVALID_LENGTH = "單字長度不符合規定喔"
    MSG_INVALID_WORD = "這不是一個合法的單字喔"

    # 擴充字庫，並統一放在設定檔中以利各元件共享
    WORD_BANK = [
        "ABOUT", "ABOVE", "ADMIT", "ADULT", "AGENT", "AGREE", "AHEAD", "ALERT",
        "ALIVE", "ALLOW", "ALONG", "ALTER", "ANGER", "ANGLE", "ANGRY", "APART",
        "APPLE", "APPLY", "ARENA", "ARGUE", "ARISE", "ARRAY", "ARROW", "ASIDE",
        "ASSET", "AUDIO", "AWAKE", "BASIC", "BASIS", "BEACH", "BEGIN", "BELOW",
        "BENCH", "BIBLE", "BIRTH", "BLACK", "BLADE", "BLIND", "BLOCK", "BLOOD",
        "BOARD", "BOOST", "BOOTH", "BOUND", "BRAIN", "BRAND", "BRAVE", "BREAD",
        "BREAK", "BRICK", "BRIDE", "BRIEF", "BRING", "BROAD", "BROWN", "BRUSH",
        "BUILD", "BUILT", "BUNCH", "BUYER", "CABIN", "CABLE", "CAMEL", "CANDY",
        "CARGO", "CARRY", "CARVE", "CATCH", "CAUSE", "CHAIN", "CHAIR", "CHAMP",
        "CHART", "CHASE", "CHEAP", "CHECK", "CHEST", "CHIEF", "CHILD", "CHINA",
        "CHOIR", "CHOSE", "CIVIL", "CLAIM", "CLASS", "CLEAN", "CLEAR", "CLERK",
        "CLICK", "CLIFF", "CLIMB", "CLOCK", "CLOSE", "CLOUD", "COACH", "COAST",
        "COCOA", "COUNT", "COURT", "COVER", "CRAFT", "CRASH", "CRAZY", "CREAM",
        "CRIME", "CROSS", "CROWD", "CROWN", "CRUDE", "CRUSH", "CYCLE", "DAILY",
        "DANCE", "DEATH", "DELAY", "DEPTH", "DIRTY", "DOZEN", "DRAFT", "DRAMA",
        "DREAD", "DREAM", "DRESS", "DRIFT", "DRINK", "DRIVE", "DROWN", "EARTH",
        "EIGHT", "ELBOW", "ELITE", "EMPTY", "ENEMY", "ENJOY", "ENTER", "ENTRY",
        "EQUAL", "ERROR", "EVENT", "EVERY", "EXTRA", "FAITH", "FALSE", "FANCY",
        "FATAL", "FEVER", "FIBER", "FIELD", "FIFTH", "FIFTY", "FIGHT", "FINAL",
        "FIRST", "FLAME", "FLASH", "FLEET", "FLIGHT", "FLUID", "FOCUS", "FORCE",
        "FORTH", "FORTY", "FORUM", "FOUND", "FRAME", "FRANK", "FRAUD", "FRESH",
        "FRONT", "FRUIT", "GIANT", "GLASS", "GLOBE", "GLOVE", "GRACE", "GRADE",
        "GRAND", "GRANT", "GRASS", "GRAVE", "GREAT", "GREEN", "GRIEF", "GROSS",
        "GROUP", "GROWN", "GUARD", "GUEST", "GUIDE", "HABIT", "HAPPY", "HARSH",
        "HAVOC", "HEART", "HEAVY", "HELLO", "HONOR", "HORSE", "HOTEL", "HOUSE",
        "HUMAN", "HUMOR", "IDEAL", "IMAGE", "INDEX", "INNER", "INPUT", "IRONY",
        "ISSUE", "IVORY", "JEANS", "JOINT", "JUDGE", "JUICE", "KNIFE", "LABEL",
        "LABOR", "LARGE", "LASER", "LATER", "LAUGH", "LAYER", "LEARN", "LEASE",
        "LEAST", "LEAVE", "LEGAL", "LEMON", "LEVEL", "LIGHT", "LIMIT", "LINKS",
        "LIVES", "LOCAL", "LOGIC", "LOOSE", "LOVER", "LOWER", "LUCKY", "LUNCH",
        "LYRIC", "MAGIC", "MAJOR", "MAKER", "MARCH", "MATCH", "MAYOR", "MEANT",
        "MEDAL", "MEDIA", "MERCY", "METAL", "MIGHT", "MINOR", "MINUS", "MIXED",
        "MODEL", "MONEY", "MONTH", "MOTOR", "MOUSE", "MOUTH", "MOVIE", "MULTI",
        "MUSIC", "NAKED", "NASTY", "NAVAL", "NEEDS", "NEVER", "NEWER", "NIGHT",
        "NOBLE", "NOISE", "NORTH", "NOTED", "NOVEL", "NURSE", "OCEAN", "OCCUR",
        "OFFER", "OFTEN", "ORDER", "OTHER", "OUTER", "OWNER", "PANEL", "PAPER",
        "PARTY", "PATCH", "PATHS", "PATIO", "PAUSE", "PEACE", "PEACH", "PEARL",
        "PEDAL", "PHASE", "PHONE", "PHOTO", "PIANO", "PIECE", "PILOT", "PINCH",
        "PITCH", "PIXEL", "PLACE", "PLAIN", "PLANE", "PLANT", "PLATE", "PLAZA",
        "PLEAD", "PLUCK", "POINT", "POKER", "POLAR", "POLES", "POUND", "POWER",
        "PRESS", "PRICE", "PRIDE", "PRIME", "PRINT", "PRIOR", "PRIZE", "PROBE",
        "PROUD", "PROVE", "PUNCH", "PUPIL", "PURSE", "QUEEN", "RADIO", "RAISE",
        "RANGE", "RAPID", "RATIO", "REACH", "REACT", "READY", "REFER", "REIGN",
        "RELAX", "REPLY", "RESET", "RIDER", "RIDGE", "RIGHT", "RIVAL", "RIVER",
        "ROBOT", "ROCKS", "ROUGH", "ROUND", "ROUTE", "ROYAL", "RULER", "RURAL",
        "SADLY", "SAFER", "SALES", "SALTY", "SANDY", "SATIN", "SAUCE", "SCALE",
        "SCARE", "SCENE", "SCENT", "SCOPE", "SCORE", "SCOUT", "SCRAP", "SCREW",
        "SHADE", "SHADOW", "SHAFT", "SHAKE", "SHARE", "SHARK", "SHARP", "SHEEP",
        "SHEER", "SHELF", "SHELL", "SHIFT", "SHINE", "SHIRT", "SHOCK", "SHOOT",
        "SHORE", "SHORT", "SHOUT", "SHOVE", "SHOWN", "SIGHT", "SIGMA", "SILENT",
        "SILLY", "SINCE", "SITES", "SIXTH", "SIXTY", "SIZES", "SKILL", "SKINNY",
        "SKIRT", "SLATE", "SLAVE", "SLEEK", "SLEEP", "SLIDE", "SLOPE", "SMALL",
        "SMART", "SMELL", "SMILE", "SMOKE", "SNACK", "SNAKE", "SOLAR", "SOLID",
        "SOLVE", "SOUND", "SOUTH", "SPACE", "SPARE", "SPARK", "SPEAK", "SPEED",
        "SPELL", "SPEND", "SPICE", "SPICY", "SPIKE", "SPINE", "SPITE", "SPLIT",
        "SPOKE", "SPORT", "SPRAY", "SQUAD", "STACK", "STAFF", "STAGE", "STAIN",
        "STAIR", "STAKE", "STALE", "STALL", "STAMP", "STAND", "STARE",
        "STARK", "START", "STATE", "STEAM", "STEEL", "STEEP", "STEER", "STEMS",
        "STEPS", "STICK", "STIFF", "STILL", "STING", "STOCK", "STONE", "STOOD",
        "STOOL", "STOPS", "STORE", "STORM", "STORY", "STRAP", "STRAW", "STRIP",
        "STUCK", "STUDY", "STUFF", "STYLE", "SUGAR", "SUITE", "SUITS", "SUNNY",
        "SUPER", "SURGE", "SWEAT", "SWEET", "SWEPT", "SWIFT", "SWING", "SWISS",
        "SWORD", "SYRUP", "TABLE", "TAKEN", "TALES", "TALON", "TANGY", "TAPES",
        "TAXIS", "TEACH", "TEETH", "TEMPO", "TENTH", "TERMS", "TEXAS", "THANK",
        "THEFT", "THEIR", "THEME", "THERE", "THESE", "THICK", "THIEF", "THIGH",
        "THING", "THINK", "THIRD", "THIRTY", "THOSE", "THREE", "THREW", "THROW",
        "THUMB", "TIGER", "TIGHT", "TILES", "TIMER", "TIMES", "TIRED", "TITLE",
        "TOAST", "TODAY", "TOKEN", "TONIC", "TOPIC", "TORCH", "TOTAL", "TOUCH",
        "TOUGH", "TOWEL", "TOWER", "TOXIC", "TRACE", "TRACK", "TRADE", "TRAIL",
        "TRAIN", "TRAIT", "TRASH", "TREAD", "TREAT", "TREND", "TRIBE", "TRICK",
        "TRIED", "TRIES", "TRUCK", "TRUTH", "TURNS", "TWICE", "TYPES", "UNDER",
        "UNION", "UNITY", "UNTIL", "UPSET", "URBAN", "USAGE", "USING", "USUAL",
        "VAGUE", "VALID", "VALUE", "VAPOR", "VEILS", "VENUE", "VIRUS", "VISIT",
        "VITAL", "VOICE", "VOWEL", "WAFER", "WAGON", "WAIST", "WASTE", "WATCH",
        "WATER", "WAVED", "WAVES", "WEARY", "WEAVE", "WEIRD", "WHEAT", "WHEEL",
        "WHERE", "WHICH", "WHILE", "WHITE", "WHOLE", "WHOSE", "WIDOW", "WIDTH",
        "WINDY", "WIVES", "WOMAN", "WOMEN", "WORDS", "WORLD", "WORRY", "WORSE",
        "WORST", "WORTH", "WOULD", "WOUND", "WRATH", "WRIST", "WRITE", "WRONG",
        "WROTE", "YACHT", "YARDS", "YEARS", "YEAST", "YIELD", "YOUNG", "YOURS",
        "YOUTH", "ZEBRA", "ZONES"
    ]